<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $_checkoutHelper = $this->helper('Magento\Checkout\Helper\Data'); ?>
<?php $_geoIpHelper = $this->helper('Jacob\Catalog\Helper\Data'); $_geoIpHelper->getIpLocation(); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="qty-wrapper">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
    </div>

    <?php if ($_product->getProductOptionsCollection()->count()): ?>
        <?php $customOptions = $_objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($_product); ?>

        <div class="product-buy-options">
            <?php foreach ($customOptions as $option): ?>
                <?php $option->setProduct($_product); ?>
                <input 
                    type="hidden" 
                    name="options[<?= $option->getId() ?>]"
                    class="product-buy-options-input"
                    value=""
                />

                <?php foreach ($option->getValues() as $optionValue): ?>
                    <div class="option-value" id="option-value-<?= $optionValue->getId() ?>">
                        <?php $optionValue->setOption($option); ?>
                        <?php $buttonTitle = __('Buy') . ' ' . $optionValue->getTitle() . ' (' . $_checkoutHelper->formatPrice($optionValue->getFinalPrice()) . ')'; ?>

                        <button 
                            type="submit"
                            title="<?= $block->escapeHtml(__('Buy')) ?>"
                            class="action tocart primary"
                            data-option-value="<?= $optionValue->getId() ?>"
                            data-option-id="<?= $option->getId() ?>"
                        >
                            <div class="original-title" style="display: none;">
                                <?= $buttonTitle ?>
                            </div>
                            <span class="display">
                                <?= $buttonTitle ?>
                            </span>
                        </button>
                    </div>
                <?php endforeach ?>
            <?php endforeach ?>
        </div>
    <?php else: ?>
        <?php $buttonTitle = __('Buy') . ' (' . $_checkoutHelper->formatPrice($_product->getFinalPrice()) . ')'; ?>
        <button type="submit"
                title="Add to Cart"
                class="action primary tocart"
                id="product-addtocart-button">
            <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
        </button>
    <?php endif ?>
</div>
<?php endif; ?>
<script>
    require([
        'jquery',
    ], function ($) {
        $(function () { 
            $('.product-buy-options button').click(function(e) {
                var button = $(e.currentTarget),
                    optionValue = button.attr('data-option-value'),
                    optionId = button.attr('data-option-id'),
                    optionInput = $('#product_addtocart_form').find('input[name="options[' + optionId + ']"]');

                if (optionInput) {
                    optionInput.val(optionValue);
                }
            });
        });
    });
</script>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
