<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $_extra = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main_menu_static_links')->toHtml() ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"delay":10, "responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>

        <?php if ($_extra): ?>
            <?php echo $_extra ?>
        <?php endif ?>
    </ul>
</nav>