<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */
$matrix = $block->getStoreMatrix();

?>
<?php if (count($block->getStores())>1 && !$block->isEuStore()): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="language-switcher-desktop">
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <div class="flag" style="background-image:url(<?= $matrix['current']['flag'] ?>)">

                </div>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($matrix['languages'] as $lang): ?>

                    <?php if ($lang['lang'] != $matrix['current']['language']): ?>
                        <li class="view-<?= $block->escapeHtml($lang['code']) ?> switcher-option">
                            <a href="#" data-post='<?= $block->getTargetStorePostData($lang['store']) ?>'>
                                <div class="dropdown-flag">
                                    <img src="<?= $lang['flag'] ?>" />
                                </div>
                                <span class="dropdown-label">
                                    <?= $lang['label'] ?>
                                </span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= strtoupper($matrix['current']['currency']) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($matrix['currencies'] as $currency): ?>

                    <?php if ($currency['currency'] != $matrix['current']['currency']): ?>
                        <li class="view-<?= $block->escapeHtml($currency['code']) ?> switcher-option">
                            <a href="#" data-post='<?= $block->getTargetStorePostData($currency['store']) ?>'>
                                <?= strtoupper($currency['currency']) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
