<?php
/*
 * The MIT License
 *
 * Copyright 2016 vConnect.dk
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * @category Magento
 * @package Vconnect_AllInOne
 * @author vConnect
 * @email kontakt@vconnect.dk
 * @template app/design/frontend/base/default/template/vconnect/aio/dk/home/scripts.phtml
 */

$allinone_data = $this->getData('allinone_data');
$allinone_config = $this->getData('allinone_config');
$dataHelper = $this->getDataHelper();

$additional_fee = $dataHelper->getAdditionalFeeData($allinone_config['system_path']);
?>

<script type="text/javascript">
require([
    'jquery',
    'jquery/ui',
    'prototype'
], function(
    jQuery
) {
    jQuery(function($){
        var shipContryVal = $('select[name="order[shipping_address][country_id]"]:last').val();
        var shipPostcodeVal = $('input[name="order[shipping_address][postcode]"]:last').val();
        var billContryVal = $('select[name="order[billing_address][country_id]"]:last').val();
        var billPostcodeVal = $('input[name="order[billing_address][postcode]"]:last').val();

        if ($('input[name="shipping_as_billing"]').length > 0 && $('input[name="shipping_as_billing"]').is(':checked')) {
           shipContryVal = '';
           shipPostcodeVal = '';
        }

        var country_id  = (shipContryVal !== '')?shipContryVal:billContryVal;
        var postcode  = (shipPostcodeVal !== '')?shipPostcodeVal:billPostcodeVal;

        <?php if ($additional_fee): ?>
        if (country_id && postcode && $('select[name="<?php echo $allinone_data['code']?>_arrival"]').length != 0) {
            getTransitInformation(country_id, postcode);
        }

        function getTransitInformation(country_id, postcode) {
            console.log('getTransitInformation called');

            var dataToSend = {
                country_id   : country_id,
                postcode     : postcode,
                service_code : 32
            };

            var eveningDelivery = false;

            $.ajax({
                url     : transitInformation,
                type    : 'POST',
                data    : dataToSend
            }).done(function (data) {
                if (!data || !data.postnord) {
                    return;
                }

                if (data.postnord.error) {
                    console.log(data.postnord.message);
                } else {
                    if(typeof data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'] !== 'undefined' && typeof data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes !== 'undefined' && typeof data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes[0] !== 'undefined' && typeof data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes[0].deliveryTime !== 'undefined' && typeof data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes[0].transitTimeInDays !== 'undefined')
                    {
                        if (data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes[0].transitTimeInDays == 1 && data.postnord['se.posten.loab.lisp.notis.publicapi.serviceapi.TransitTimeResponse'].transitTimes[0].deliveryTime == '21:00') {
                            eveningDelivery = true;
                        }
                    }

                    if (eveningDelivery) {
                        $('#<?php echo $allinone_data['code'] ?>_additional_fee_element').show();
                    } else {
                        $('#<?php echo $allinone_data['code'] ?>_additional_fee_element').hide();
                    }
                }
            });
        }
        <?php endif; ?>

        $('div[data-code=<?php echo $allinone_data['code'] ?>]').appendTo($('input[value=<?php echo $allinone_data['code'] ?>]').parent());
    });
});
</script>
