<?php
/*
 * The MIT License
 *
 * Copyright 2016 vConnect.dk
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * @category Magento
 * @package Vconnect_AllInOne
 * @author vConnect
 * @email kontakt@vconnect.dk
 * @template app/design/frontend/base/default/template/vconnect/aio_base/dk/commercial/tabHeader.phtml
 */

$allinone_data = $this->getData('allinone_data');
$allinone_config = $this->getData('allinone_config');
$dataHelper = $this->getDataHelper();
?>

<div data-code="<?php echo $allinone_data['code'] ?>" class="aio-options">
    <?php if(!empty($allinone_config['delivery_time'])): ?>
    <label for="<?php echo $allinone_data['code'] ?>_deliverytime"><?php echo __("Label arrival time commercial:") ?></label><br /><?php echo $allinone_config['delivery_time']; ?><br />
    <?php endif;?>

    <?php $count_arrival = count($allinone_config['arrival']); ?>
    <?php if ($count_arrival): ?>
    <label for="<?php echo $allinone_data['code'] ?>_arrival"><?php echo __('Label arrival commercial:') ?></label>
    <select style="<?php if ($count_arrival == 1): ?> display: none; <?php endif; ?>" id="<?php echo $allinone_data['code'] ?>_arrival" name="<?php echo $allinone_data['code'] ?>_arrival">
        <?php foreach ($allinone_config['arrival'] as $value => $label) : ?>
            <option value="<?php echo $value ?>"><?php echo __($label) ?></option> 
        <?php endforeach; ?>
    </select>
    <?php if ($count_arrival == 1 && isset($label)): ?>
    <span><?php echo __($label) ?></span>
    <?php endif; ?>
    <br/>
    <?php endif; ?>

    <?php $count_delivery = count($allinone_config['delivery']); ?>
    <?php if ($count_delivery): ?>
    <label for="<?php echo $allinone_data['code'] ?>_delivery"><?php echo __('Label delivery commercial:') ?></label>
    <select style="<?php if ($count_delivery == 1): ?> display: none; <?php endif; ?>" id="<?php echo $allinone_data['code'] ?>_delivery" name="<?php echo $allinone_data['code'] ?>_delivery">
        <?php foreach ($allinone_config['delivery'] as $value => $label) : ?>
            <?php if (is_array($label)): ?>
                <optgroup label="<?php echo  $value?>">            
                    <?php foreach ($label as $j=>$k): ?>
                        <option value="<?php echo is_int($j)?$k:$j ?>"><?php echo __($k) ?></option>
                    <?php endforeach; ?>
                 </optgroup>           
            <?php else: ?>
               <option value="<?php echo __($value); ?>"><?php echo __($label) ?></option> 
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
    <?php if ($count_delivery == 1 && isset($label)): ?>
    <span><?php echo __($label) ?></span>
    <?php endif; ?>
    <br/>
    <textarea name="<?php echo $allinone_data['code'] ?>_other" class="other-txt" placeholder="<?php echo __('Write place') ?>"></textarea>
    <?php endif; ?>
</div>
